[project]
name = "tickets-servicedesk-parse"
version = "0.1.0"
description = "Авто-парсинг тикетов Intraservice и Telegram-бот для выгрузки JSON"
authors = [
    {name = "mihailovily"}
]
requires-python = ">=3.12,<4.0"
dependencies = [
    "requests (>=2.34.2,<3.0.0)",
    "beautifulsoup4 (>=4.15.0,<5.0.0)",
    "python-dotenv (>=1.2.3,<2.0.0)",
    "python-telegram-bot (>=22.0,<23.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
